### ISSUE TITLE
Is 21/0/2 fully completed?

### ISSUE THREAD

**Issue by duolabb** [Potatosynthesis/Babamorphosis#1]
Is 21/0/2 fully completed?

First of all I have to say that this self-made level is very interesting! Thank you very much, because it allows me to regain the fun of playing Baba is You.

I have completed LEVEL 1-12, LEVEL A/B/C, LEVEL Extra 1-3, LEVEL END, Babamorphosis and map.
I got two bonuses in map and Extra 3.
So is 21/0/2 completely completed? If not, can you tell me the number when it is fully completed.

Thank you again for making such an excellent level.

**Comment by Potatosynthesis** [comment]
23/0/3 Is the full completion.

Currently I'm making a bigger level pack which consists of this pack and Babasynthesis (both updated!) and you can look forward to it.

**Comment by duolabb** [comment]
> 23/0/3 Is the full completion.
> 
> Currently I'm making a bigger level pack which consists of this pack and Babasynthesis (both updated!) and you can look forward to it.

Thank you for replying so quickly!

It seems that there are still many things I haven't considered. I will work hard to achieve full completion as soon as possible.

Looking forward to your new works!

**Comment by Potatosynthesis** [comment]
Lol I didn't really expect a comment here so it's pure luck that I happened to visit github just as you commented.

Some levels in the current version of Babamorphosis are flawed imo and this pack is already months old so I will change them in the new pack. Such levels include level 5 (unclear objective) and level 6 (alternate solution).
